version: '3.7'

services:
  traefik:
    image: traefik:v2.6
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik/traefik.yml:/etc/traefik/traefik.yml
      - traefik-ssl-certs:/ssl-certs
    networks:
      - intranet

  kratos-migrate:
    image: oryd/kratos:v0.8.0-alpha.3-sqlite
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true&mode=rwc
    volumes:
      - type: volume
        source: "kratos-sqlite"
        target: "/var/lib/sqlite"
        read_only: false
      - type: bind
        source: "./config/kratos"
        target: "/etc/config/kratos"
    command: -c "/etc/config/kratos/kratos.yml" migrate sql -e --yes
    restart: on-failure
    networks:
      - intranet

  kratos-selfservice-ui-node:
    image: oryd/kratos-selfservice-ui-node:v0.8.0-alpha.3
    environment:
      - PORT=4455
      - KRATOS_PUBLIC_URL=http://kratos:4433/
      - KRATOS_BROWSER_URL=http://127.0.0.1/.ory/kratos/public/
      - JWKS_URL=http://oathkeeper:3001/.well-known/jwks.json
      - SECURITY_MODE=jwks
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kui.entrypoints=web"
      - "traefik.http.routers.kui.rule=(Host(`127.0.0.1`) || Host(`localhost`)) && PathPrefix(`/kui/`)"
      - "traefik.http.middlewares.kui-stripprefix.stripprefix.prefixes=/kui"
      - "traefik.http.routers.kui.middlewares=oathkeeper@file,kui-stripprefix"
      - "traefik.http.services.kui.loadbalancer.server.port=4455"
    restart: on-failure
    networks:
      - intranet

  kratos:
    image: oryd/kratos:v0.8.0-alpha.3-sqlite
    depends_on:
      - kratos-migrate
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true
      - LOG_LEVEL=trace
      - SERVE_PUBLIC_BASE_URL=http://127.0.0.1/.ory/kratos/public/
    command: serve -c "/etc/config/kratos/kratos.yml" --dev --watch-courier
    volumes:
      - type: volume
        source: "kratos-sqlite"
        target: "/var/lib/sqlite"
        read_only: false
      - type: bind
        source: "./config/kratos"
        target: "/etc/config/kratos"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kratos.entrypoints=web"
      - "traefik.http.routers.kratos.rule=(Host(`127.0.0.1`) || Host(`localhost`)) && PathPrefix(`/.ory/kratos/public`)"
      - "traefik.http.middlewares.kratos-stripprefix.stripprefix.prefixes=/.ory/kratos/public"
      - "traefik.http.routers.kratos.middlewares=oathkeeper@file,kratos-stripprefix"
      - "traefik.http.services.kratos.loadbalancer.server.port=4433"
    restart: unless-stopped
    networks:
      - intranet

  oathkeeper:
    image: oryd/oathkeeper:v0.38
    depends_on:
      - kratos
    command:
      serve -c "/etc/config/oathkeeper/oathkeeper.yml"
    environment:
      - LOG_LEVEL=debug
    volumes:
      - type: bind
        source: "./config/oathkeeper"
        target: "/etc/config/oathkeeper"
    restart: on-failure
    networks:
      - intranet

  # Mail service for development
  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - '4436:4436'
      - '4437:4437'
    networks:
      - intranet

networks:
  intranet:

volumes:
  kratos-sqlite:
  traefik-ssl-certs:
    driver: local
