-
  id: "ory:kui:anonymous"
  match:
    url: "http://<{127.0.0.1,localhost}>/kui/<{registration*,login*,verification*,error*,recovery*,**.css,**.js,**.png}{/,}>"
    methods:
      - GET
  authenticators:
    - handler: anonymous
  authorizer:
    handler: allow
  mutators:
    - handler: noop

-
  id: "ory:kui:protected"
  match:
    url: "http://<{127.0.0.1,localhost}>/kui/<{,settings*,welcome}>"
    methods:
      - GET
  authenticators:
    - handler: cookie_session
  authorizer:
    handler: allow
  mutators:
    - handler: id_token
  errors:
    - handler: redirect
      config:
        to: http://127.0.0.1/kui/login

-
  id: "ory:kratos:public"
  match:
    url: "http://<{127.0.0.1,localhost}>/.ory/kratos/public/<**>"
    methods:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
  authenticators:
    - handler: noop
  authorizer:
    handler: allow
  mutators:
    - handler: noop
