# oathkeeper: "http://127.0.0.1:3000"
# kratos public: "http://kratos:4433"
# kratos ui: "http://kratos-selfservice-ui-node:4455"

-
  id: "ory:kui:anonymous"
  upstream:
    preserve_host: true
    url: "http://kratos-selfservice-ui-node:4455"
    strip_path: /kui
  match:
    url: "http://127.0.0.1:3000/kui/<{registration,login,verification,error,recovery,verify,auth/*,**.css,**.js,**.png}{/,}>"
    methods:
      - GET
  authenticators:
    - handler: anonymous
  authorizer:
    handler: allow
  mutators:
    - handler: noop

-
  id: "ory:kui:protected"
  upstream:
    preserve_host: true
    url: "http://kratos-selfservice-ui-node:4455"
    strip_path: /kui
  match:
    url: "http://127.0.0.1:3000/kui/<{,debug,dashboard,settings,welcome}>"
    methods:
      - GET
  authenticators:
    - handler: cookie_session
  authorizer:
    handler: allow
  mutators:
    - handler: id_token
  errors:
    - handler: redirect
      config:
        to: http://127.0.0.1:3000/kui/login

-
  id: "ory:kratos:public"
  upstream:
    preserve_host: true
    url: "http://kratos:4433"
    strip_path: /.ory/kratos/public
  match:
    url: "http://127.0.0.1:3000/.ory/kratos/public/<**>"
    methods:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
  authenticators:
    - handler: noop
  authorizer:
    handler: allow
  mutators:
    - handler: noop
